### ISSUE TITLE
boot process fail

### ISSUE THREAD

**Issue by alepee** [TinkerBoard/android-6.0.1_u-boot#1]
After flashing sdcard with Etcher and [the image distributed on asus tinkerboard page](https://www.asus.com/us/Single-Board-Computer/Tinker-Board/#tinker-board-Download) I get these errors on boot:

![](http://get.antoine.io/3S3f1D0O271J/IMG_20180204_105044.jpg)

I did that several times, with no success

**Comment by jamess-huang** [comment]
May I know the model name of your sdcard ?

**Comment by alepee** [comment]
Hi @jamess-huang 

I used a PNY MicroSDHC 8Go
https://www.amazon.fr/dp/B017VQDX9U/

It works perfectly with other system, you think it could have an impact ?

**Comment by jamess-huang** [comment]
1. could you try the latest android image from our website ?
https://www.asus.com/us/Single-Board-Computer/Tinker-Board/HelpDesk_Download/
select others for the OS to download the latest image

2. could you try to use another sdcard ?

**Comment by alepee** [comment]
The latest image did not work and finally succeeded with another sdcard. Thanks for your help @jamess-huang
